# Generated by Django 4.1.4 on 2022-12-12 03:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email')),
                ('is_email_valid', models.BooleanField(default=False, verbose_name='email проверен')),
                ('email_valid_d', models.DateTimeField(blank=True, null=True, verbose_name='дата последней валидации email')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате '+79999999999'", regex='^\\+?1?\\d{9,15}$')], verbose_name='номер телефона')),
                ('is_phone_valid', models.BooleanField(default=False, verbose_name='номер телефона проверен')),
                ('phone_valid_d', models.DateTimeField(blank=True, null=True, verbose_name='дата последней валидации телефона')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=150, verbose_name='отчество')),
                ('car_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='номер авто')),
                ('user_photo', models.ImageField(upload_to='users_photos', verbose_name='фото пользователя')),
                ('is_staff', models.BooleanField(default=False, verbose_name='персонал?')),
                ('created_d', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='EntranceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.CharField(choices=[('auto', 'AutoNumber'), ('face', 'FaceRecognition')], max_length=4)),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='дата входа')),
                ('exit_date', models.DateTimeField(blank=True, null=True, verbose_name='дата выхода')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_story', to=settings.AUTH_USER_MODEL, verbose_name='id связанного юзера')),
            ],
            options={
                'verbose_name': 'История входа и выхода',
                'verbose_name_plural': 'Истории входа и выхода',
            },
        ),
    ]
