# Generated by Django 4.1.4 on 2022-12-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='created_d',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_operator',
        ),
    ]
